name: EmoWeather
main: com.emoweather.EmoWeather
version: 1.0
api-version: 1.21
commands:
  mood:
    description: Set your current mood
    usage: /mood <mood>[see available moods with moodlist]
  moodlist:
    description: Show available moods
    usage: /moodlist
  moodgui:
    description: Open mood selection GUI
    usage: /moodgui